### ISSUE TITLE
Logos, and more data

### ISSUE THREAD

**Issue by jamescridland** [fancysoups/podcast-privacy#2]
This looks great, and I plan to implement this on Podnews shortly.

https://github.com/opawg/podcast-hosts contains logos for all podcast hosts, links to privacy policies, and a URL pattern. I'd be very happy to merge this data. 

https://github.com/opawg/podcast-prefixes also contains data for prefix analytics companies.

**Comment by shahruz** [comment]
It'd be great to integrate both of those. 

Would you like to submit a pull request with the additional data? Otherwise I can take a look in the next couple days at integrating that data myself. Thanks!

**Comment by shahruz** [comment]
This is now merged in and released as part of v0.0.6, and I've added a script to help keep things in sync in the future. Thanks @jamescridland!
