### ISSUE TITLE
"Dynamic Advertising" = dynamic content

### ISSUE THREAD

**Issue by jamescridland** [fancysoups/podcast-privacy#3]
This is a pedantic point, but one that is important...

Podcast hosts that offer dynamic content insertion may use this feature for advertising, but may not do so.

One podcast in the US uses it to inject local news stories into their podcast; another in Australia uses it to add the latest news headlines.

I'd caution about describing this feature as 'Dynamic Advertising'. It is properly described as 'Dynamic Content Insertion'.

**Comment by shahruz** [comment]
This is a great suggestion, I'm going to make this modification in the canary branch. 

Ideally any strings included like abilities are generic enough to not need changing often.
