### ISSUE TITLE
Now implemented on Podnews

### ISSUE THREAD

**Issue by jamescridland** [fancysoups/podcast-privacy#4]
Here's the page from [This American Life](https://podnews.net/podcast/201671138)...

![Screen Shot 2020-10-31 at 2 07 32 pm](https://user-images.githubusercontent.com/231941/97770812-73f3fb80-1b82-11eb-81f2-96148d83644a.png)

Would love to help with logos and other data.

**Comment by jamescridland** [comment]
In fact; I've pulled the data into my own database - the data here is a little too light and incomplete.

* [Here are the prefixes](https://github.com/opawg/podcast-prefixes)

* [Here are the hosts](https://github.com/opawg/podcast-hosts)

I'd love to work together to improve this data; and could easily output a variant of this for your JSON code.

**Comment by shahruz** [comment]
Thanks! Closing this issue to continue the similar discussion in https://github.com/fancysoups/podcast-privacy/issues/2.
